spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:http://localhost:8097'
  autoconfigure:
    exlcude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

spring-doc:
  apid-docs:
    enabled: false
  swagger-ui:
    enabled: false